import signUpTest from './user.test';
import userLoginTest from './userLogin.test';
import allRequestTest from './request.test';
import userProfileInformation from './getUserAnEditProfileInfo.test';
import twoWayTrip from './twoWayTrip.test';
import rejectRequest from './rejectRequest.test';
import socialLogin from './socialLogin.test';
import multiCityRequest from './multicityRequest.test';
import routeExistance from './app.test';
import rememberMe from './rememberMe.test';
import commentTest from './comment.test';
import editNotification from './editNotification.test';
import notOwner from './mockEditNotification/loginAsNotOwner';
import emptyObject from './mockEditNotification/emptyInput';
import eventEmail from './mockEditNotification/emailtesting';

eventEmail();
routeExistance();
signUpTest();
userLoginTest();
userProfileInformation();
twoWayTrip();
allRequestTest();
commentTest();
rejectRequest();
multiCityRequest();
rememberMe();
editNotification();
notOwner();
emptyObject();
socialLogin();
